server:
  port: 8082

eureka:
  instance:
   hostname: localhost

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: Cart-Service-Application
          uri: http://localhost:9006/
          predicates:
            - Path=/api/v1/**
        - id: CustomerService
          uri: http://localhost:9005/
          predicates:
            - Path=/api/v1/**
            
        - id: Glass-Service
          uri: http://localhost:9003/
          predicates:
            - Path=/api/v1/**
            
          
            
        - id: Lens_Cart_Management_Authentication_Authorization
          uri: http://localhost:8080/
          predicates:
            - Path=/api/**
            
        - id: CustomerService
          uri: http://localhost:9005/
          predicates:
            - Path=/api/v1/**     
       
            
           
            
          
  