server:
  port: 8082

eureka:
  instance:
   hostname: localhost

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: Lens_Cart
          uri: http://localhost:9001/
          predicates:
            - Path=/api/v1/**

#        - id: Customer-MicroService
#          uri: http://localhost:8086/
#          predicates:
#            - Path=/api/v1/**